<?php

namespace App\classes;

use App\interfaces\MessengerInterface;

class SmsMessenger extends AppMessenger
{
    public function send()
    {
        dd('from sms');
        return parent::send(); // TODO: Change the autogenerated stub
    }
}